---
title: "Cell Summary Tables"
output:
  html_document:
    css: "../Templates/my-CSS-theme.css"
date: "`r format(Sys.time(), '%B %d, %Y')`"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo=FALSE,
                      message=FALSE,
                      warning=FALSE)

source(
  here::here("Scripts/Libraries.R"),
  local = knitr::knit_global(),
  echo = FALSE,
  verbose  = FALSE
)

source(here("Scripts/Functions.R"), local = knitr::knit_global())
source(here("Templates/Theme-options.R"), local = knitr::knit_global())


save_RDS_files <- "no"
```


```{css increase-div-width}
div.main-container {
  max-width: 1400px !important;
}

```

```{r import-data}
# Import and process evoked current data
make_normalized_EPSC_data(filename = "Data/Sample-eEPSC-data.csv",
                          current_type = "eEPSC",
                          min_time_value = 0,
                          max_time_value = 25,
                          interval_length = 5,
                          baseline_length = 5)
make_pruned_EPSC_data(data = raw_eEPSC_df,
                      current_type = "eEPSC",
                      min_time_value = 0,
                      max_time_value = 25,
                      baseline_length = 5,
                      interval_length = 1)

make_normalized_EPSC_data(filename = "Data/Sample-sEPSC-data.csv",
                          current_type = "sEPSC",
                          min_time_value = 0,
                          max_time_value = 25,
                          interval_length = 5,
                          baseline_length = 5)
make_pruned_EPSC_data(data = raw_sEPSC_df,
                      current_type = "sEPSC",
                      min_time_value = 0,
                      max_time_value = 25,
                      baseline_length = 5,
                      interval_length = 1)
```


# Number of cells

```{r cell-count-table}
cell_characteristics <- read.csv(here("Data/sample-cell-characteristics.csv"))
```


```{r cell-characteristics-table}
cell_characteristics %>%
  rename_with(str_to_title) %>% 
  group_by(Treatment, Sex, Category) %>%
  summarize('Number of cells' = n()) %>%
  reactable(
    columns = list('Number of cells' = colDef(
      style = function(value) {
        if (value < 7) {
          color <- "#950606"
        } else {
          color <- "#000000"
        }
        list(color = color, fontWeight = "bold")
      }
    )),
    highlight = TRUE
  )
```

# Cell Information

```{r functions-dataframes-for-table}
make_cell_summary_df <- function(cell_characteristics_df,
                                 include_all_treatments = "yes",
                                 list_of_treatments = NULL,
                                 include_all_categories = "yes",
                                 list_of_categories = NULL) {
  cell_characteristics_for_table <- cell_characteristics_df %>%
    mutate(
      R_a = lapply(str_split(R_a, pattern = ", "), FUN = as.numeric),
      R_a = lapply(R_a, FUN = replace_na, replace = 0),
      letter = factor(letter)
    )
  
  table_data <-
    merge(pruned_eEPSC_df_for_table, pruned_sEPSC_df_for_table, by = "letter") %>%
    merge(., cell_characteristics_for_table, by = "letter") %>%
    merge(., treatment_names_and_colours, by = "treatment") %>%
    select(
      c(
        letter,
        display_names,
        treatment,
        synapses,
        sex,
        P1_transformed,
        spont_amplitude_transformed,
        R_a,
        X,
        Y,
        age,
        animal,
        category,
        cell,
        colours
      )
    ) %>%
    rename_with(str_to_title) %>%
    mutate(across(c(X, Y), round, -1))
  
  if (include_all_treatments == "yes") {
    if (!is.null(list_of_treatments)) {
      warning(
        "include_all_treatments = \"yes\", but you included a list of treatments to filter. All treatments will be used."
      )
    }
    
  } else {
    if (is.null(list_of_treatments)) {
      stop(
        "include_all_treatments = \"",
        include_all_treatments,
        "\", but list_of_treatments is NULL.",
        "\nDid you forget to add a list of treatments?"
      )
    }
    
    if (!is.character(list_of_treatments)) {
      stop(
        "include_all_treatments = \"",
        include_all_treatments,
        "\", but list_of_treatments is not a character object.",
        "\nDid you forget to add a list of treatments?"
      )
    }
    
  }
  # Category filter
  
  if (include_all_categories == "yes") {
    if (!is.null(list_of_categories)) {
      warning(
        "include_all_categories = \"yes\", but you included a list of categories to filter. All categories will be used."
      )
    }
    
  } else {
    if (is.null(list_of_categories)) {
      stop(
        "include_all_categories = \"",
        include_all_categories,
        "\", but list_of_categories is NULL.",
        "\nDid you forget to add a list of categories?"
      )
    }
    
    if (!is.character(list_of_categories)) {
      stop(
        "include_all_categories = \"",
        include_all_categories,
        "\", but list_of_categories is not a character object.",
        "\nDid you forget to add a list of categories?"
      )
    }
    
    table_data <- table_data %>%
      filter(Treatment %in% list_of_treatments)
  }
  
  assign("summary_table_data", table_data, envir = .GlobalEnv)
}


make_interactive_summary_table <- function(dataframe) {
  cell_table <- reactable(
    data = dataframe,
    defaultSorted = c("Category", "Treatment", "Animal"),
    filterable = TRUE,
    showPageSizeOptions = TRUE,
    elementId = "cell-table",
    defaultPageSize = 15,
    defaultColDef = colDef(vAlign = "center", headerVAlign = "center"),
    columns = list(
      Colours = colDef(show = FALSE),
      Letter = colDef(
        name = "Letter",
        sticky = "left",
        style = list(borderRight = "1px solid #eee"),
        headerStyle = list(borderRight = "1px solid #eee")
      ),
      Display_names = colDef(name = "Treatment"),
      Treatment = colDef(show = FALSE),
      Sex = colDef(
        name = "Sex",
        filterMethod = JS(
          "function(rows, columnId, filterValue) {
        return rows.filter(function(row) {
          return String(row.values[columnId]).toUpperCase() === filterValue.toUpperCase()
        })
      }"
        )
      ),
      P1_transformed = colDef(
        name = "eEPSC amplitude (pA)",
        filterable = FALSE,
        cell = react_sparkline(
          dataframe,
          line_color_ref = "Colours",
          show_area = TRUE,
          area_opacity = 1
        )
      ),
      Spont_amplitude_transformed = colDef(
        name = "sEPSC amplitude (pA)",
        filterable = FALSE,
        cell = react_sparkline(
          dataframe,
          line_color_ref = "Colours",
          show_area = TRUE,
          area_opacity = 1
        )
      ),
      R_a = colDef(
        name = "Ra (MΩ)",
        filterable = FALSE,
        cell = react_sparkline(
          dataframe,
          line_color_ref = "Colours",
          labels = c("first", "last"),
          decimals = 1
        )
      )
    )
  )
  cell_table
}
```


```{r make-cell-summary-table}
make_cell_summary_df(
  cell_characteristics_df = cell_characteristics,
  include_all_treatments = "yes",
  list_of_treatments = c("Control"),
  include_all_categories = "no",
  list_of_categories = c("2")
)

make_interactive_summary_table(dataframe = summary_table_data)
```


